version: "3.9"
services:
  pg-db:
    container_name: composepostgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - myapp-network
      
networks:
  myapp-network:
